
const SUBPIXEL = 1.0 / 16.0;
// const MAX_DELTA_TIME = 60.0 / 1000.0;
const MAX_DELTA_TIME = 60.0 / 1000.0;
const SUBSUBSUBPIXEL = SUBPIXEL * SUBPIXEL * SUBPIXEL;
const SUBSUBSUBPIXEL_DELTA_TIME = SUBSUBSUBPIXEL * MAX_DELTA_TIME;

const OBJECT_FALL = 0x00300 * SUBSUBSUBPIXEL_DELTA_TIME;
const OBJECT_MAX_FALL = 0x04000 * SUBSUBSUBPIXEL_DELTA_TIME;
const OBJECT_DEAD_BOUNCE = 0x04000 * SUBSUBSUBPIXEL_DELTA_TIME;
const OBJECT_DEAD_X_VEL = 0x00C00 * SUBSUBSUBPIXEL_DELTA_TIME;
const MESH_BOX_EXPAND = 3.0;

export {
  SUBPIXEL,
  MAX_DELTA_TIME,
  SUBSUBSUBPIXEL,
  SUBSUBSUBPIXEL_DELTA_TIME,
  OBJECT_FALL,
  OBJECT_MAX_FALL,
  OBJECT_DEAD_BOUNCE,
  OBJECT_DEAD_X_VEL,
  MESH_BOX_EXPAND
}